language: node_js
node_js:
  - 12
  - 10
cache:
  directories:
  - node_modules
  - example/node_modules
script:
  - npm test
  - npm run build
  - cd example
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: example/build
  on:
    branch: master
